const toggle=document.querySelector('.menu-toggle');
const nav=document.querySelector('#site-nav');
const mobile=window.matchMedia('(max-width:760px)');
function setMenu(open,{returnFocus=false}={}){nav.hidden=mobile.matches&&!open;toggle.setAttribute('aria-expanded',String(mobile.matches&&open));toggle.innerHTML=open?'Close <span aria-hidden="true">−</span>':'Menu <span aria-hidden="true">+</span>';if(returnFocus)toggle.focus();}
if(toggle&&nav){toggle.hidden=false;setMenu(false);toggle.addEventListener('click',()=>setMenu(toggle.getAttribute('aria-expanded')!=='true'));nav.addEventListener('click',e=>{if(e.target.closest('a')&&mobile.matches)setMenu(false,{returnFocus:true});});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&toggle.getAttribute('aria-expanded')==='true')setMenu(false,{returnFocus:true});});mobile.addEventListener('change',()=>setMenu(false));}
const copy=document.querySelector('#copy-email');
if(copy&&navigator.clipboard){copy.hidden=false;copy.addEventListener('click',async()=>{const status=document.querySelector('#copy-status');try{await navigator.clipboard.writeText('khsuhan100@gmail.com');status.textContent='Email address copied.';}catch{status.textContent='Copy unavailable. Select the email address above or open it in your mail app.';}});}
const load=document.querySelector('#load-scene');
if(load){let scene=null,loading=false;const host=document.querySelector('#scene-host'),poster=document.querySelector('#scene-poster'),controls=document.querySelector('#scene-controls'),status=document.querySelector('#scene-status');const descriptions={sense:'Sense — sensors turn the surrounding world into signals.',compute:'Compute — the controller interprets inputs and chooses a response.',act:'Act — motors turn a command into physical movement.'};
const reset=()=>{scene?.dispose();scene=null;host.classList.remove('active');poster.hidden=false;controls.hidden=true;controls.querySelectorAll('[data-part]').forEach(b=>b.setAttribute('aria-pressed','false'));load.hidden=false;load.disabled=false;load.innerHTML='Explore in 3D <span aria-hidden="true">↗</span>';};load.hidden=false;
load.addEventListener('click',async()=>{if(loading)return;loading=true;load.disabled=true;status.textContent='Opening the miniature workbench…';try{let timer;const module=await Promise.race([import('./scene.js'),new Promise((_,reject)=>{timer=setTimeout(()=>reject(new Error('Scene load timeout')),12000);})]).finally(()=>clearTimeout(timer));host.classList.add('active');scene=module.createScene(host,()=>{reset();status.textContent='3D is unavailable. The static illustration remains available.';});poster.hidden=true;controls.hidden=false;load.hidden=true;status.textContent='Illustrative robot study. Choose a subsystem or rotate the view.';controls.querySelector('button').focus();}catch{reset();status.textContent='3D could not load. You can still explore every project below.';}finally{loading=false;}});
controls.querySelectorAll('[data-part]').forEach(button=>button.addEventListener('click',()=>{scene?.highlight(button.dataset.part);controls.querySelectorAll('[data-part]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));status.textContent=descriptions[button.dataset.part];}));document.querySelector('#rotate-scene').addEventListener('click',()=>scene?.rotate());document.querySelector('#close-scene').addEventListener('click',()=>{reset();status.textContent='A miniature study of how sensing, computation and motion connect.';load.focus();});}
