import { projects } from "./projects.mjs";
const esc = (s) =>
  String(s).replace(
    /[&<>"']/g,
    (c) =>
      ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[
        c
      ],
  );
export const domain = "https://suhankhadka.com.np";
const tags = (p) =>
  p.tags.map((t) => `<span class="tag">${esc(t)}</span>`).join("");
const repo = (p) => `https://github.com/SuhanVerse/${p.repo}`;
const flows = {
  visiobot: ["Patrol", "Detect", "Approach"],
  edumentx: ["Discover", "Compare", "Enroll"],
  robovault: ["Request", "Approve", "Return"],
};
const visual = (p, large = false) =>
  p.slug === "arduino-robot"
    ? `<img src="/assets/media/arduino-${large ? "1200" : "640"}.webp" alt="Arduino robot build with ultrasonic sensor and four wheels" width="1200" height="800" loading="lazy" decoding="async">`
    : `<div class="project-outline"><span class="eyebrow">${esc(p.tags[0])}</span><ol>${flows[p.slug].map((label) => `<li>${label}</li>`).join("")}</ol><span class="outline-label">Implementation overview</span></div>`;
const projectCard = (p) => `<article class="project">
  <a class="project-media" href="/projects/${p.slug}/" aria-label="Explore ${esc(p.short)}">${visual(p)}</a>
  <div class="project-detail"><div class="project-meta"><span>${esc(p.category)}</span><span>${esc(p.status)}</span></div>
  <h3><a href="/projects/${p.slug}/">${esc(p.short)}</a></h3><p class="project-summary">${esc(p.summary)}</p>
  <div class="project-bottom"><div class="tags">${tags(p)}</div><div class="project-links"><a href="/projects/${p.slug}/" aria-label="Read ${esc(p.short)} details">Details ↗</a><a href="${repo(p)}" aria-label="View ${esc(p.short)} source on GitHub">Source ↗</a></div></div></div>
</article>`;
export function shell(title, description, path, body) {
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#f4f1e9"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><meta name="author" content="Suhan Khadka"><link rel="canonical" href="${domain}${path}"><meta property="og:type" content="website"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${domain}${path}"><meta property="og:image" content="${domain}/assets/media/social-card.png"><meta property="og:image:alt" content="Suhan Khadka — Robotics, embedded systems and software"><meta name="twitter:card" content="summary_large_image"><link rel="icon" href="/assets/favicon.ico"><link rel="stylesheet" href="/assets/site.css"><script type="module" src="/assets/js/main.js"></script></head><body>
<a class="skip" href="#main">Skip to content</a><header class="header"><div class="wrap header-inner"><a href="/" class="brand" aria-label="Suhan Khadka home"><span class="brand-mark" aria-hidden="true">sk.</span>Suhan Khadka</a><button class="menu-toggle" type="button" aria-expanded="false" aria-controls="site-nav" hidden>Menu <span aria-hidden="true">+</span></button><nav class="nav" id="site-nav" aria-label="Main navigation"><a href="/#work">Selected work</a><a href="/#about">About</a><a href="/#notes">Lab notes</a><a class="nav-contact" href="/#contact">Let's talk <span aria-hidden="true">↗</span></a></nav></div></header>
<main id="main">${body}</main><footer class="footer"><div class="wrap"><span>© ${new Date().getUTCFullYear()} Suhan Khadka</span><span>Lalitpur, Nepal · Built with curiosity.</span><a href="https://github.com/SuhanVerse/Portfolio_Website">Site source ↗</a></div></footer></body></html>`;
}
const contact = `<section id="contact" class="contact"><div class="wrap contact-grid"><div><div class="eyebrow">04 / Get in touch</div><h2>Let’s build something.</h2><p>Interested in robotics, an idea for a useful tool, or something we could build together? I'd like to hear about it.</p></div><div><a class="contact-email" href="mailto:khsuhan100@gmail.com">khsuhan100@gmail.com <span aria-hidden="true">↗</span></a><div class="contact-actions"><button type="button" id="copy-email" hidden>Copy email address</button><span class="eyebrow">Lalitpur, Nepal</span></div><p id="copy-status" class="contact-status" role="status" aria-live="polite"></p><div class="socials"><a href="https://github.com/SuhanVerse">GitHub ↗</a><a href="https://www.linkedin.com/in/suhan-khadka/">LinkedIn ↗</a><a href="https://x.com/ultraman_62">X ↗</a><a href="https://www.facebook.com/suhan.khadka.35/">Facebook ↗</a></div></div></div></section>`;
export function home() {
  return shell(
    "Suhan Khadka — Robotics, Embedded Systems & Software",
    "Computer Engineering student in Lalitpur, Nepal. Explore my robotics, embedded systems, perception and software projects.",
    "/",
    `
<section class="hero"><div class="wrap"><div class="hero-grid"><div><div class="eyebrow"><span class="dot"></span>Computer engineering · Lalitpur, Nepal</div><h1>Code that meets<br>the <em>real world.</em></h1><p class="hero-copy">I'm Suhan. I bring software and hardware together through robotics, embedded systems, and practical software.</p><div class="actions"><a class="button" href="#work">Explore my work <span aria-hidden="true">↘</span></a><a class="text-link" href="/assets/cv.pdf">View résumé <span aria-hidden="true">↗</span></a></div></div><div class="workbench"><div class="bench-top"><span class="eyebrow">The workbench</span><span class="eyebrow">Sense / Compute / Act</span></div><div class="bench-visual"><img id="scene-poster" src="/assets/media/robot-poster.webp" alt="Illustrative miniature robot with sensors, a controller and driven wheels" width="900" height="692" fetchpriority="high"><div id="scene-host" class="scene-host" aria-hidden="true"></div><span id="scene-phase" class="scene-phase" hidden>Sense</span><button id="load-scene" class="button scene-load" type="button" hidden>Explore in 3D <span aria-hidden="true">↗</span></button></div><div class="scene-controls" id="scene-controls" role="group" aria-label="Robot demonstration controls" hidden><button data-part="sense" type="button" aria-pressed="false">01 Sense</button><button data-part="compute" type="button" aria-pressed="false">02 Compute</button><button data-part="act" type="button" aria-pressed="false">03 Act</button><button id="auto-scene" type="button" aria-pressed="true">Auto cycle</button><button id="pause-scene" type="button" aria-pressed="false">Pause motion</button><button id="rotate-scene" type="button">Rotate view</button><button id="close-scene" type="button">Close 3D</button></div><p id="scene-status" class="scene-note" role="status">Illustrative robot demo: sensor scan, controller signal and wheel motion.</p></div></div><div class="hero-foot"><span>HARDWARE IN HAND. SOFTWARE WITH PURPOSE.</span><span>SCROLL TO SELECTED WORK ↓</span></div></div></section>
<section class="section" id="work"><div class="wrap"><div class="section-head"><div><div class="eyebrow">01 / Selected work</div><h2>Selected projects.</h2></div><p>Hardware builds, robotics simulations and software. Each project links to its implementation and current limitations.</p></div><div class="projects">${projects.map(projectCard).join("")}</div></div></section>
<section class="section capabilities"><div class="wrap"><div class="section-head"><div><div class="eyebrow">How I build</div><h2>Tools I work with.</h2></div></div><div class="cap-grid"><div class="cap"><span class="index">01 / HARDWARE</span><h3>Robotics & embedded</h3><p>Working with microcontrollers, sensors and motor control. Learning by wiring, programming and seeing what happens on the bench.</p><a href="/projects/arduino-robot/">Arduino · C/C++ · ESP32 ↗</a></div><div class="cap"><span class="index">02 / INTELLIGENCE</span><h3>Perception & autonomy</h3><p>Exploring how a system interprets its surroundings and responds, through computer vision and robot simulation.</p><a href="/projects/visiobot/">Python · ROS 2 · Computer vision ↗</a></div><div class="cap"><span class="index">03 / SOFTWARE</span><h3>Apps & backend systems</h3><p>Building interfaces and APIs around practical needs, from finding a tutor to managing equipment in a robotics club.</p><a href="/projects/edumentx/">TypeScript · React Native · APIs ↗</a></div></div></div></section>
<section class="section" id="about"><div class="wrap about-grid"><div><img class="portrait" src="/assets/media/suhan-640.webp" srcset="/assets/media/suhan-320.webp 320w, /assets/media/suhan-640.webp 640w" sizes="(max-width:760px) 260px, 360px" alt="Suhan Khadka outdoors" width="640" height="800" loading="lazy"><p class="portrait-caption">Suhan Khadka / Lalitpur, Nepal</p></div><div class="about-copy"><div class="eyebrow">02 / A little about me</div><h2>Curious about the<br>whole system.</h2><p>I'm a Computer Engineering student at National College of Engineering. What interests me most is the point where an idea becomes something you can interact with—a moving robot, a sensor response, or an app that helps someone.</p><p>My work spans Arduino experiments, ROS 2 simulation, and software projects. Along the way, I'm exploring tools like Rust and Fusion 360, and learning through the NCE Robotics Club.</p><div class="timeline"><div class="timeline-row"><span class="time">Currently</span><div><h3>B.E. Computer Engineering</h3><p>National College of Engineering</p></div></div><div class="timeline-row"><time datetime="2025-05">Since 2025</time><div><h3>Member · NCE Robotics Club</h3><p>Robotics, practical exploration and learning with peers.</p></div></div><div class="timeline-row"><time datetime="2025">2025</time><div><h3>Fusion 360 bootcamp</h3><p>NCE Robotics Club · Introduction to CAD and modeling.</p></div></div><div class="timeline-row"><time datetime="2024">2024</time><div><h3>MERN stack & UI/UX workshops</h3><p>NCE IT Club · Software development and interface design.</p></div></div></div><a class="text-link" href="/assets/cv.pdf">Read my résumé ↗</a></div></div></section>
<section class="section" id="notes"><div class="wrap"><div class="section-head"><div><div class="eyebrow">03 / Lab notes</div><h2>Experiments & learning.</h2></div><p>Code, notes and experiments from my ongoing study.</p></div><div class="notes-list"><a class="note" href="https://github.com/SuhanVerse/LSPP60days-Challenge_2025"><span class="index">01</span><div><h3>60 days, from Rust to Python & AI</h3><p>A learning repository of exercises, embedded experiments and data projects.</p></div><span class="arrow" aria-hidden="true">↗</span></a><a class="note" href="https://github.com/SuhanVerse/Embedded_Hardware_Projects"><span class="index">02</span><div><h3>Small boards, hands-on experiments</h3><p>Arduino and ESP32 explorations with OLED displays and touch input.</p></div><span class="arrow" aria-hidden="true">↗</span></a><a class="note" href="https://github.com/SuhanVerse/visiobot"><span class="index">03</span><div><h3>Connecting perception with motion</h3><p>Robot descriptions, navigation configuration and vision experiments in VisioBot.</p></div><span class="arrow" aria-hidden="true">↗</span></a></div></div></section>${contact}`,
  );
}
export function casePage(p) {
  return shell(
    `${p.short} — Suhan Khadka`,
    p.summary,
    `/projects/${p.slug}/`,
    `<div class="wrap"><section class="case-hero"><a class="breadcrumb" href="/#work">← Back to selected work</a><div class="eyebrow">${esc(p.category)} / ${esc(p.status)}</div><h1>${esc(p.short)}</h1><p class="case-intro">${esc(p.intro)}</p><div class="actions"><a class="button" href="${repo(p)}">Explore the repository ↗</a><span class="eyebrow">${esc(p.short)}</span></div><div class="case-visual ${p.slug === "arduino-robot" ? "case-photo" : "case-overview"}">${visual(p, true)}</div><p class="media-caption">${p.slug === "arduino-robot" ? "Actual build photograph" : "Implementation overview · See the source links below"}</p></section><div class="case-body"><aside class="case-aside" aria-label="Project resources"><h2>Tools & technologies</h2><div class="tags">${tags(p)}</div><h2>Inspect the work</h2>${p.evidence.map(([label, path]) => `<a href="${repo(p)}/blob/main/${path}">${esc(label)} ↗</a>`).join("")}</aside><div class="case-content"><section><h2>The problem</h2><p>${esc(p.problem)}</p></section><section><h2>Inside the implementation</h2><p>${esc(p.implementation)}</p>${p.decisions.map(([h, t]) => `<h3>${esc(h)}</h3><p>${esc(t)}</p>`).join("")}</section><section><h2>What the evidence shows</h2><p>The linked repository contains the implementation and supporting artifacts for this project. Follow the source links to inspect the details.</p><h3>Current limitations</h3><p>${esc(p.limits)}</p><div class="case-next"><h2>The next iteration</h2><p>${esc(p.next)}</p></div></section><a class="text-link" href="/#work">← Explore another project</a></div></div></div>${contact}`,
  );
}
